#!/bin/env python
import socket, os, select

HOST="irc.zepler.net"
PORT=6667
NICK="pipebot"
IDENT="pipebot"
REALNAME="pipebot"
CHANNEL="#test_channel"

s=socket.socket()
s.connect((HOST, PORT))
s.setblocking(0)

s.send("NICK %s\r\n" % NICK)
s.send("USER %s %s bla :%s\r\n" % (IDENT, HOST, REALNAME))
s.send("JOIN %s\r\n" % CHANNEL)
s.send("PRIVMSG %s %s\r\n" % (CHANNEL, "I like bees") )

if not os.path.exists("/tmp/pipebot"):
    os.mkfifo("/tmp/pipebot")


irc_buf = ""
pipe_buf = ""

def privmsg(socket, target, msg):
    socket.send( "PRIVMSG %s %s\r\n" % (target, msg) )
    pass

def open_fifo():
    fifofd = os.open( "/tmp/pipebot",
                      os.O_RDONLY | os.O_NONBLOCK )
    return fifofd

fifofd = open_fifo()

while True:
    ready = select.select( [fifofd,s], [], [fifofd] )
    print "SELECT", ready

    if s in ready[0]:
        irc_buf += s.recv(100)

        while "\n" in irc_buf:
            lp = irc_buf.find("\n")

            l = irc_buf[0:lp]
            irc_buf = irc_buf[lp+1:]

            print l
            if l[:4] == "PING":
                print "ping"
                resp = l.replace( "I", "O", 1 )
                print "resp:", resp
                s.send( resp )

                privmsg(s, CHANNEL, "I just told the server to pong off.")
                continue

    if fifofd in ready[0]:
        print "fifo in ready[0]"
        pipe_buf += os.read(fifofd, 100)
        print len(pipe_buf)
        print "\"%s\"" % pipe_buf

        while "\n" in pipe_buf:
            nlpos = pipe_buf.find("\n")
            line = pipe_buf[0:nlpos]
            pipe_buf = pipe_buf[nlpos+1:]

            privmsg(s, CHANNEL, line)

    if fifofd in ready[2]:
        print "fifo in ready[2]"

        os.close(fifofd)
        fifofd = open_fifo()
        
