#!/usr/bin/env python

from __future__ import with_statement

import os
import sys

PIPE_PATH="/tmp/hash-srobo"

try:
    with os.open( PIPE_PATH, os.O_WRONLY | os.O_NONBLOCK ) as fifofd:
        fifofd.write(' '.join(sys.argv))
except OSError:
    pass
